### ISSUE TITLE
Error with unrecognized music format

### ISSUE THREAD

**Issue by WilliamQLiu** [justinmeister/Mario-Level-1#5]
I cloned the repo and I'm using Python 2.7.6 on Mac with pygame 1.9.2a0.  When I run the game, I'm able to start a new game, but get this error right after I see the Mario has 3 lives black screen.

Traceback (most recent call last):
  File "mario_level_1.py", line 15, in <module>
    main()
  File "/Users/williamliu/GitHub/Mario-Level-1/data/main.py", line 18, in main
    run_it.main()
  File "/Users/williamliu/GitHub/Mario-Level-1/data/tools.py", line 75, in main
    self.update()
  File "/Users/williamliu/GitHub/Mario-Level-1/data/tools.py", line 41, in update
    self.flip_state()
  File "/Users/williamliu/GitHub/Mario-Level-1/data/tools.py", line 48, in flip_state
    self.state.startup(self.current_time, persist)
  File "/Users/williamliu/GitHub/Mario-Level-1/data/states/level1.py", line 40, in startup
    self.sound_manager = game_sound.Sound(self.overhead_info_display)
  File "/Users/williamliu/GitHub/Mario-Level-1/data/game_sound.py", line 15, in **init**
    self.set_music_mixer()
  File "/Users/williamliu/GitHub/Mario-Level-1/data/game_sound.py", line 22, in set_music_mixer
    pg.mixer.music.load(self.music_dict['main_theme'])
pygame.error: Unrecognized music format

**Comment by marcellovirzi** [comment]
It worked also for me!! Great!

OS X Yosemite 10.10.3
Python 3.4.2
Pygame 1.9.1

Thank's guys

**Comment by agudulin** [comment]
Reinstalling `sdl_mixer` worked for me too, thanks.

**Comment by RyanHartje** [comment]
I still have the same issue, after trying to install libvorbis, and uninstall both libogg and libvorbis, and reinstalling sdl_mixer. Is there a full list of dependencies somewhere I'm overlooking?

**Comment by RyanHartje** [comment]
Fixed my issue, here's what was going on:

SDL Mixer wasn't compiling with smpeg support because no docs include smpeg as a dependency. Also compiled SDL Mixer (just config, make, make install, nothing fancy). 

For any of those having the same issue, I wrote this up on a Stack Overflow question with the same issue. 

You can ignore step2 if you have already installed pygame. Also change pip3 to pip and remove python3 from the brew install list if you plan to use python27 or something

Step 1:
Install all Pygame deps for Mac with Brew (if you don't have brew, look up how to install first)
```ssh
    brew install python3 hg sdl sdl_image sdl_ttf portmidi smpeg 
```
Step 2:
Install PyGame
```ssh
    pip3 install hg+http://bitbucket.org/pygame/pygame
```
Step 3:
Download sdl-mixer source code from: https://www.libsdl.org/projects/SDL_mixer/release-1.2.html

Untar the tar.gz file with tar zxvf:
```ssh
    tar zxvf SDL_mixer-1.2.12.tar.gz
    cd SDL_mixer-1.2.12
    ./configure
    make
    sudo make install
```
Step 4:
Run your pygame code and see if it fixes your dependency issue


I hope this helps others who come to this with the same issue I had on OS X Yosemite

**Comment by samilokan** [comment]
Unfortunately first brew installation did not work. But uninstall and reinstall works! Thanks @hamidnazari
